Update M.yml

diff --git a/.github/workflows/M.yml b/.github/workflows/M.yml
--- a/.github/workflows/M.yml
+++ b/.github/workflows/M.yml
@@ -37,10 +37,12 @@ jobs:
           python3 \
           zip
 
-    - name: Setup KernelSU-Next
+        - name: Setup KernelSU-Next
       run: |
+        cd $GITHUB_WORKSPACE
+        ls
+        test -d drivers || { echo "Kernel source not found"; exit 1; }
         curl -LSs https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh | bash -
-
     - name: Enable KernelSU
       run: |
         echo "CONFIG_KSU=y" >> arch/arm64/configs/vendor/redwood_QGKI_defconfig
